twilio:
  account_sid: ACe26ec523399667f01d6a8c8122895005
  auth_token: "enter key"
  trial_number: "enter wp trial no"

bezkoder:
  app:
    jwtSecret: "enter secret"
    jwtExpirationMs: 900000

spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: juzunoglualihan@gmail.com
    password: "enter password"
    port: '587'

  security:
    user:
      name: alihan
      password: alihan
      roles: USER_ROLE

  datasource:
    driver-class-name: org.postgresql.Driver
    username: sample
    url: jdbc:postgresql://localhost:5432/sample
    password: sample
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
